### ISSUE TITLE
Inconsistency in options `image_name` vs `image.name`

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#545]
Note the difference:
```
$ mlem deploy run docker_container docker_container.mlem -m lyrics2emoji --image_name mlem-lyrics2emoji
$ mlem build docker -m lyrics2emoji --image.name mlem-lyrics2emoji
```

**Comment by mike0sv** [comment]
The difference if because deploy has a separate field `image_name` for this option and build has `image` field of type `DockerImage` that has nested `name` field. We either need to use separate field in build or nested field in deploy. I thing the latter is better since `DockerImage` also has some other fields like `tag`
